on: [push, pull_request, workflow_dispatch]

jobs:
  codeql-sast:
    name: CodeQL SAST scan
    uses: alphagov/govuk-infrastructure/.github/workflows/codeql-analysis.yml@main
    permissions:
      security-events: write

  dependency-review:
    name: Dependency Review scan
    uses: alphagov/govuk-infrastructure/.github/workflows/dependency-review.yml@main

  # This matrix job runs the test suite against multiple Ruby versions
  test_matrix:
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.2, 3.3]
    runs-on: ubuntu-latest
    env:
      GOVUK_CONTENT_SCHEMAS_PATH: vendor/publishing-api/content_schemas
    steps:
      - uses: actions/checkout@v5
      - name: Checkout Publishing API for content schemas
        uses: actions/checkout@v5
        with:
          repository: alphagov/publishing-api
          ref: main
          path: vendor/publishing-api
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake

  # Branch protection rules cannot directly depend on status checks from matrix jobs.
  # So instead we define `test` as a dummy job which only runs after the preceding `test_matrix` checks have passed.
  # Solution inspired by: https://github.community/t/status-check-for-a-matrix-jobs/127354/3
  test:
    needs: test_matrix
    runs-on: ubuntu-latest
    steps:
      - run: echo "All matrix tests have passed 🚀"

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          rubygems: latest
      - uses: actions/setup-node@v5.0.0
        with:
          node-version: lts/* # use the latest LTS release
      - run: yarn install
      - env:
          GEM_HOST_API_KEY: ${{ secrets.ALPHAGOV_RUBYGEMS_API_KEY }}
        run: |
          VERSION=$(ruby -r rubygems -e "puts Gem::Specification::load('content_block_tools.gemspec').version")
          GEM_VERSION=$(gem list --exact --remote content_block_tools)
          
          if [ "${GEM_VERSION}" != "content_block_tools (${VERSION})" ]; then
            gem build content_block_tools.gemspec
            gem push "content_block_tools-${VERSION}.gem"
          fi
          
          if ! git ls-remote --tags --exit-code origin v"${VERSION}"; then
            git tag v"${VERSION}"
            git push --tags
          fi
